// Resume Template for Typst
// This template is used by tools/generate-pdf.py when Typst is the PDF engine.
//
// Template variables are injected by the Python script based on resume_template.yaml.
// This file serves as documentation and a fallback template structure.

// Page setup (values injected from template)
#set page(
  paper: "us-letter",  // or "a4"
  margin: (
    top: 0.5in,
    bottom: 0.5in,
    left: 0.5in,
    right: 0.5in,
  ),
)

// Typography setup
#set text(
  font: "Helvetica",  // or "Georgia" for serif
  size: 11pt,
)

// Color definitions (injected from template)
#let primary = rgb("#2C3E50")
#let secondary = rgb("#7F8C8D")
#let body-color = rgb("#333333")

// Header styling
#let resume-header(name, contact) = {
  align(left)[
    #text(size: 24pt, weight: "bold", fill: primary)[#name]
  ]
  text(fill: secondary)[#contact]
  line(length: 100%, stroke: 0.5pt + secondary)
}

// Section heading styling
#let section-heading(title) = {
  v(0.8em)
  text(size: 1.1em, weight: "bold", fill: primary)[
    #upper(title)
  ]
  line(length: 100%, stroke: 0.5pt + secondary)
  v(0.4em)
}

// Position/job entry styling
#let position-entry(title, company, dates, bullets) = {
  grid(
    columns: (1fr, auto),
    [*#title*\ #company],
    align(right)[#text(fill: secondary)[#dates]]
  )
  for bullet in bullets {
    [- #bullet]
  }
  v(0.6em)
}

// Education entry styling
#let education-entry(degree, school, dates) = {
  grid(
    columns: (1fr, auto),
    [*#degree*\ #text(fill: secondary)[#school]],
    align(right)[#text(fill: secondary)[#dates]]
  )
  v(0.4em)
}

// Skills styling (inline format)
#let skills-inline(skills) = {
  skills.join(" • ")
}

// Skills styling (tags format)
#let skills-tags(skills) = {
  for skill in skills {
    box(
      fill: luma(240),
      inset: (x: 0.4em, y: 0.2em),
      radius: 2pt,
    )[#skill]
    h(0.3em)
  }
}

// Example usage (commented out - actual content is generated by Python):
//
// #resume-header(
//   "John Doe",
//   "john@email.com | (555) 123-4567 | linkedin.com/in/johndoe"
// )
//
// #section-heading("Experience")
//
// #position-entry(
//   "Senior Software Engineer",
//   "Tech Company Inc.",
//   "Jan 2020 - Present",
//   (
//     "Led development of microservices architecture",
//     "Improved system performance by 40%",
//     "Mentored team of 5 junior developers",
//   )
// )
//
// #section-heading("Skills")
//
// #skills-inline(("Python", "JavaScript", "Kubernetes", "AWS"))
